# Generated by Django 4.2.13 on 2024-09-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='fname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bio',
            name='lname',
            field=models.CharField(max_length=20),
        ),
    ]
