# Generated by Django 4.2.13 on 2024-10-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_bio_fname_alter_bio_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='bio',
            old_name='lname',
            new_name='lastname',
        ),
    ]
