# Generated by Django 4.2.13 on 2024-10-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_fname_bio_firstname_rename_lname_bio_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='email',
            field=models.EmailField(default='ronald@gmail.com', max_length=50),
        ),
    ]
