# Generated by Django 4.2.13 on 2024-10-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_bio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='select', max_length=2),
        ),
    ]
