# Generated by Django 4.2.13 on 2024-10-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_bio_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='dob',
            field=models.DateField(default='2020-05-05'),
        ),
    ]
