# Generated by Django 4.2.13 on 2024-10-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_bio_address_bio_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bio',
            new_name='Enroll',
        ),
    ]
