# Generated by Django 4.2.13 on 2024-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_bio_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
    ]
