# Generated by Django 4.2.13 on 2024-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_enroll_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='telephone',
            field=models.CharField(default='08149801749', max_length=11),
            preserve_default=False,
        ),
    ]
