# Generated by Django 4.2.13 on 2024-10-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_enroll_passport_alter_enroll_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='Enroll_date',
            field=models.DateField(default='2020-03-02', verbose_name='Enrollment Date'),
        ),
    ]
