# Generated by Django 4.2.13 on 2024-10-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_enroll_enroll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='address',
            field=models.CharField(default='', max_length=30, verbose_name='Address'),
        ),
    ]
