# Generated by Django 4.2.13 on 2024-10-11 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_enroll_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='Enroll_date',
        ),
        migrations.AddField(
            model_name='enroll',
            name='enroll_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enrollment Date'),
        ),
    ]
