# Generated by Django 4.2.13 on 2024-10-11 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_enroll_enroll_date_enroll_enroll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='enroll_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Enrollment Date'),
        ),
    ]
